library(tidygraph)
library(dplyr)
library(ggraph)
source(here::here("scripts", "functions.R"))
kea3_networks = create_kea3_networks()
saveRDS(kea3_networks, file = here::here("data", "outputs", "rds_files", "kea3_networks.rds"))
